spring:
  application:
    name: learnable
  cloud:
    vault:
      scheme: http
      authentication: TOKEN
      token: ${VAULT_TOKEN}
  config:
    import: vault://
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    url: ${LOCAL_DB_URL}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true